#!/bin/bash
# Copyright © 2022 Kris Nóva <nova@nivenly.org>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Initialize the test
echo " --> [Test] Clearing existing logs"
rm -vrf /var/log/nginx-proxy-analysis/*
mkdir -p /var/log/nginx-proxy-analysis
touch /var/log/nginx-proxy-analysis/error.log
touch /var/log/nginx-proxy-analysis/access.log

# Load the Dashboard
echo " --> [Test] GoAccess dashboard..."
./dashboard &

# Load the Proxy server
echo " --> [Test] Launching proxy server..."
./proxy &
sleep 1
NGINX_PID=$(pgrep nginx | head -1) # The worker holds the connections

# Upstream Case (Happy Path)
echo " --> [Case: happy] Launching upstream server [basic-socket-unix]..."
./cases/basic-server-unix &
./stats $NGINX_PID
./traffic
./stats $NGINX_PID
read -p "Press any key to continue"
pkill -f -9 basic-server-unix

# Upstream Case (Sad Path)
echo " --> [Case: sad] Launching upstream server [basic-socket-unix]..."
./cases/bad-server-unix &
C2=$(pgrep C2 | head -1)
./stats $NGINX_PID
./traffic
./stats $NGINX_PID
read -p "Press any key to continue"
pkill -f -9 bad-socket-unix

# Exit
echo ""
pkill -f -9 nginx
pkill -f -9 goaccess
echo ""
echo "Finished." 
exit 0
