#!/bin/bash
# Copyright © 2022 Kris Nóva <nova@nivenly.org>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Perform a task a given number of times
echo "  --> Sending 10000 requests to localhost:80"
for i in {1..10000}
do
 printf "."
 curl -o /dev/null --header "Connection: keep-alive" --silent localhost:80 & # Note: this must match the nginx.conf listen directive
done
echo ""
